<?xml version="1.0"?>
<!DOCTYPE skins [
  <!ENTITY % links.att 'name CDATA #REQUIRED'>
  <!ENTITY % link.att 'name CDATA #REQUIRED href CDATA #REQUIRED'>
  <!ELEMENT skins (skin*)>
  <!ELEMENT skin (description)>
  <!ATTLIST skin name CDATA #REQUIRED
                 url  CDATA #REQUIRED>
  <!ELEMENT description (#PCDATA)>
  ]>
  
<skins>
  <skin name="testskin"
        url="http://www.apache.org/~nicolaken/whiteboard/forrestskins/">
    <description>
      Based on the standard forrest-site skin.
    </description>
  </skin>
  <skin name="testskin2"
        url="http://www.apache.org/~nicolaken/whiteboard/forrestskins/">
    <description>
      Based on the standard forrest-site skin.
    </description>
  </skin>
</skins> 
